### ISSUE TITLE
Handle +/- Inf values when pushing Raw data to InfluxDB

### ISSUE THREAD

**Issue by choukha** [equinor/gordo#404]
Handle or Pre-process the Data points having +Inf or -Inf values, before writing to the Influx.

[Inf Values Influx Write Error Trace.txt](https://github.com/equinor/gordo-components/files/3492579/Inf.Values.Influx.Write.Error.Trace.txt)

**Comment by epa095** [comment]
It seems like the two possible solutions we have with influx is to either write nothing for these values, or write some arbitrary large value. I am more inclined to do the first, since `inf` is outside the domain being presented in the graphs, but I also understand that it can be useful to distinguish `inf` from the lack of a value. 

I think it would be useful to ask someone who knows the data what `inf` typically means (if there is a typical meaning at all). Is it just another encoding of `nan`?

**Comment by milesgranger** [comment]
I'd also be inclined to the first option, but could we also update that 'position' in Grafana to place an orange line (or something to that effect) at such places, as a flag? And drop the `inf` so as to not wreck the graph itself.

**Comment by epa095** [comment]
Tja, the flagging is a good idea, but it gets a bit messy. The annotations today come from the sql metadata database, which the client (luckily) has no relation to. Maybe it is possible to get annotations from influx, but I dont think thats easy. A variant of that is to create a new timeseries for each tag, which has 1 stored only where the original series is `inf`, then the information is at least stored. But thats also a bit messy :-/  

Edit: [Maybe it is less hard than I thought. ](https://grafana.com/docs/features/datasources/influxdb/#annotations)
