### ISSUE TITLE
Rewrite the way model metadata is fetched

### ISSUE THREAD

**Issue by flikka** [equinor/gordo#422]
Today the model metadata is fetched after model building by looking deep down in a Pipeline, or even in fields in BaseModels. This code is too complicated, recursive and not very robust to for example Gordo models not at the end of a Pipeline.

There should be a better way, a way that is more similar to logging, where inside the (custom) model class the metadata is written to some thing, and then this is fetched from the metadata thing afterwards.

**Comment by epa095** [comment]
Proposed solution: Create a context manager like [this](https://docs.python.org/3/library/contextlib.html#contextlib.contextmanager) which sets a thread local variable 
```python
tls = threading.local()
tls.__magic_metdata_object = {}
```
Remember to remove the variable in the `finally` step. 

Then create a function `log_metadata` which logs a key-value to this dictionary if it exists, otherwise does nothing (maybe log something on `debug`). This can then be used like this
```python
with MetadatCollector as m:
    model.fit()
    if m:
        globalmetadata.append(m)
```

**Comment by epa095** [comment]
I also propose, but are not settled, that in the `log_metadata` it could check if the key is already in the dictionary. If it is then maybe add it with a numeric (and increasing) suffix. E.g. `alpha-2` if `alpha` is already set. This is a way to enable several instances of the same class to all log the same keys.

**Comment by ryanjdillon** [comment]
Similar but orthogonal to #182.
